#!/bin/bash
#
make distclean >/dev/null
rm -rf release
mkdir -p release/Xsaitekpanels/64 &&

make distclean >/dev/null
qmake -spec linux-g++-4.8-64 && make &&
cp plugin/liblin.xpl.so release/Xsaitekpanels/64/lin.xpl
if [ $? != 0 ] ; then
  exit
fi


make distclean >/dev/null
qmake -spec linux-g++-4.8-32 && make &&
cp plugin/liblin.xpl.so release/Xsaitekpanels/lin.xpl
if [ $? != 0 ] ; then
  exit
fi
make distclean >/dev/null
#

