#!/bin/bash
#
cd X-Plane_Github_Plugins/xsaitekpanels &&
./build4linux &&
ssh -v Williams-Mac-Pro.local ". ~/.bash_profile && cd X-Plane_Github_Plugins/xsaitekpanels && git pull && ./build4mac"
exec $SHELL
#

