#!/bin/bash
#
# How to run
# cd Xsaitekpanels repo
# ./build-XP12-Xsaitekpanels_lin_WithDocker_win_mac_WithCmake_OnLinux

rm -r Xsaitekpanels/win_x64/*
rm -r Xsaitekpanels/lin_x64/*
rm -r Xsaitekpanels/mac_x64/*
rm -r src/build-lin/*

# Windows build

 rm -r build/*
 cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake
 cmake --build ./build -v
 cp ./build/win.xpl ./Xsaitekpanels/win_x64/Xsaitekpanels.xpl


# Linux build

# building a version for Ubuntu 20.04
# It does not have the debugging info the other build has

(cd docker; make)
cp src/build-lin/lin.xpl Xsaitekpanels/lin_x64/Xsaitekpanels.xpl

# rm -r build/*
# cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
# cmake --build ./build -v
# cp ./build/lin.xpl ./Xsaitekpanels/lin_x64/Xsaitekpanels.xpl


# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-11.3.cmake
cmake --build ./build -v
cp ./build/mac.xpl ./Xsaitekpanels/mac_x64/Xsaitekpanels.xpl


cp docs/XsaitekpanelsUsersManual.pdf Xsaitekpanels/Documentation/
cp docs/ChangeLog.txt Xsaitekpanels/Documentation/
cp docs/Xsaitekpanelsdatarefs.txt Xsaitekpanels/Documentation/
cp docs/Linux_Users_Please_Read.txt Xsaitekpanels/Documentation/
cp docs/51-Xsaitekpanels.rules Xsaitekpanels/Documentation/

exec $SHELL
#

