#!/bin/bash
#
# How to run
# ./xp11_xsaitekpanels_plugin_builder/xsaitekpanels/build-XP11-Xsaitekpanels_win_WithDocker_mac_lin_WithCmake_OnLinux

cd xp11_xsaitekpanels_plugin_builder/xsaitekpanels &&
mkdir -p release/Xsaitekpanels/64 &&
mkdir -p release/Xsaitekpanels/mac_x64 &&
mkdir -p release/Xsaitekpanels/mac_arm &&

rm -r src/build-win/*

rm -r Xsaitekpanels/64/*


# Have to make Windows build with Docker Ubuntu 18.04
# Because it will not build correctly with Cmake on Ubuntu 20.04
(cd docker; make)

cd src
mkdir -p build
rm -r build/*
cd build
cmake ..
make VERBOSE=1
cd /home/bill/xp11_xsaitekpanels_plugin_builder/xsaitekpanels
cp src/build/lin.xpl release/Xsaitekpanels/64/

cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xsaitekpanels_plugin_builder/xsaitekpanels/src/Toolchain-ubuntu-osxcross-11.3-x86_64.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xsaitekpanels_plugin_builder/xsaitekpanels
cp src/build/mac.xpl release/Xsaitekpanels/mac_x64/

# cd src
# rm -r build/*
# cd build
# cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xsaitekpanels_plugin_builder/xsaitekpanels/src/Toolchain-ubuntu-osxcross-11.3-arm_64.cmake ..
# make VERBOSE=1
# cd /home/bill/xp11_xsaitekpanels_plugin_builder/xsaitekpanels
# cp src/build/mac.xpl release/Xsaitekpanelsmac_arm/

# lipo -create -output Xsaitekpanels/mac_x64/Xsaitekpanels.xpl release/Xsaitekpanels/mac_x64/Xsaitekpanels.xpl release/Xsaitekpanels/mac_arm/Xsaitekpanels.xpl

cp src/build-win/win.xpl Xsaitekpanels/64/
cp release/Xsaitekpanels/64/lin.xpl Xsaitekpanels/64/
cp release/Xsaitekpanels/mac_x64/mac.xpl Xsaitekpanels/64/

# cp docs/Xsaitekpanels.pdf Xsaitekpanels/Documentation/Xsaitekpanels.pdf

exec $SHELL
#

