#!/bin/bash
#
scp src/bippanel.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/bippanel.cpp
scp src/inireader.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/inireader.cpp
scp src/inireader.h Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/inireader.h
scp src/multidata.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/multidata.cpp
scp src/multipanel.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/multipanel.cpp
scp src/radio1data.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/radio1data.cpp
scp src/radio2data.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/radio2data.cpp
scp src/radio3data.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/radio3data.cpp
scp src/radiopanels.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/radiopanels.cpp
scp src/readinifile.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/readinifile.cpp
scp src/saitekpanels.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/saitekpanels.cpp
scp src/saitekpanels.h Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/saitekpanels.h
scp src/switchdata.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/switchdata.cpp
scp src/switchpanel.cpp Williams-Mac-Pro.local:xp10plugins_github/Xsaitekpanels_test/src/switchpanel.cpp
