#!/bin/bash
#
# This shell script creates a fat XPlane-plugin 
# (see http://www.xsquawkbox.net/xpsdk/mediawiki/BuildInstall#Fat_Plugins)
# for Windows, Linux and MacOS, all in 32 and 64 bits
#
# The script runs on a Linux host and cross-compiles the plugin for
# all the mentioned architectures. It has been tested on a Fedora 22
# x86_64 system.
#
# There is quite a number of prerequisites that must be installed
# in order for this script to run:
#
# Prerequisite to build X-Plane plugins:
#   - X-Plane SDK available at http://www.xsquawkbox.net/xpsdk/mediawiki/Download
#     [Make sure to use a version >=2.1.1 for 64 bit compatibility!,
#      I used 2.1.3. Download it and unzip it in THIS folder,
#      which will actually populate the SDK directory.]
#
#
# Build system for MACOS target:
#   - osxcross [(https://github.com/tpoechtrager/osxcross) 
#               with OSX SDK installed (see osxcross README file)
#               This will give you a bit of work, since it will
#               recompile the clang compiler on linux. But it 
#               actually works!]
#

# CHANGE THIS: define location and version of OSX SDK installed
# with osxcross. 
# OSXSDK=~/src/osxcross/target/SDK/MacOSX10.10.sdk
OSXSDK=~/X-Plane_OsxCrossBuild/osxcross/target/SDK/MacOSX10.11.sdk


# echo commands
set -x

# set name and location of output directory
TARGETDIR=target/Xsaitekpanels

# create output directory structure
rm -rf $TARGETDIR
mkdir -p $TARGETDIR
mkdir $TARGETDIR/64

# build hybrid OSX version
make -f Makefile_mac clean
OS=MACOSX CC=o64-clang++ SDK=$OSXSDK TARGET=$TARGETDIR/mac.xpl make -f Makefile_mac

# clean up
make -f Makefile_mac clean
